version: "3.9"

services:
  migrate:
    container_name: kovan
    build:
      context: ./
      dockerfile: migrate.Dockerfile
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    env_file:
      - .env