version: "3.9"

services:
  ethereum:
    container_name: twitter-ethereum
    image: trufflesuite/ganache-cli
    networks:
      - ethereum
    ports:
      - "8545:8545"
    logging:
      driver: none
  
  test:
    container_name: twitter-contract-test
    build:
      context: ./
      dockerfile: tests.Dockerfile
    depends_on: 
      - ethereum
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - host=ethereum
    networks:
      - ethereum
networks: 
  ethereum: